name: CI For My Personal Website

on:
  workflow_dispatch: 

jobs: 
  ci_for_my_personal_website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login registry.gitlab.com -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Switch Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        id: buildx
        with:
          install: true

      - name: Docker Build, Push
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64 \
            --tag registry.gitlab.com/burakcanyukselen/medium-container-registry/mypersonalwebsite .